name: Validation
on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run unit tests
        run: |
          cd ultraocr
          mvn -B package --file pom.xml
